In [11]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [12]:
 #Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Husavik,IS,2020-11-05 21:19:54,66.04,-17.34,48.20,39,40,18.34
1,1,Cabo San Lucas,MX,2020-11-05 21:19:14,22.89,-109.91,87.01,58,5,10.04
2,2,Kununurra,AU,2020-11-05 21:19:54,-15.77,128.73,77.00,88,2,3.36
3,3,Bechem,GH,2020-11-05 21:18:05,7.09,-2.02,76.26,76,76,1.63
4,4,Mahebourg,MU,2020-11-05 21:19:02,-20.41,57.70,73.40,78,75,5.82

In [13]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [19]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [70]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [71]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
# Heatmap of percent wind
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [38]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [39]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Cabo San Lucas,MX,2020-11-05 21:19:14,22.89,-109.91,87.01,58,5,10.04
2,2,Kununurra,AU,2020-11-05 21:19:54,-15.77,128.73,77.00,88,2,3.36
3,3,Bechem,GH,2020-11-05 21:18:05,7.09,-2.02,76.26,76,76,1.63
6,6,Biak,ID,2020-11-05 21:19:25,-0.91,122.88,77.72,76,64,1.81
7,7,Puerto Ayora,EC,2020-11-05 21:19:02,-0.74,-90.35,77.00,69,20,20.80
8,8,Hobyo,SO,2020-11-05 21:19:55,5.35,48.53,80.13,79,98,7.83
10,10,Kapaa,US,2020-11-05 21:18:37,22.08,-159.32,80.60,83,40,9.17
12,12,Saint-Georges,GD,2020-11-05 21:19:37,12.06,-61.75,86.00,70,20,13.87
13,13,Gainesville,US,2020-11-05 21:19:56,29.65,-82.32,78.80,61,75,14.99
19,19,Hilo,US,2020-11-05 21:19:06,19.73,-155.09,84.20,62,40,8.05

In [74]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp    Lat     Lng Hotel Name
1   Cabo San Lucas      MX     87.01  22.89 -109.91
2        Kununurra      AU     77.00 -15.77  128.73
3           Bechem      GH     76.26   7.09   -2.02
6             Biak      ID     77.72  -0.91  122.88
7     Puerto Ayora      EC     77.00  -0.74  -90.35
8            Hobyo      SO     80.13   5.35   48.53
10           Kapaa      US     80.60  22.08 -159.32
12   Saint-Georges      GD     86.00  12.06  -61.75
13     Gainesville      US     78.80  29.65  -82.32
19            Hilo      US     84.20  19.73 -155.09

In [42]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [56]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
hotel_df

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Cabo San Lucas,MX,87.01,22.89,-109.91,Hotel Tesoro Los Cabos
2,Kununurra,AU,77.00,-15.77,128.73,Hotel Kununurra
3,Bechem,GH,76.26,7.09,-2.02,Orange Hotel
6,Biak,ID,77.72,-0.91,122.88,Kost Ariz
7,Puerto Ayora,EC,77.00,-0.74,-90.35,Finch Bay Galapagos Hotel
...,...,...,...,...,...,...
522,Axim,GH,79.83,4.87,-2.24,AXIM BEACH RESORT AND SPA
523,Vila Do Maio,CV,78.80,15.13,-23.22,Residence 'I Delfini'
527,Coahuayana,MX,88.93,18.73,-103.68,Hotel Los Arcos
528,Jacareacanga,BR,86.54,-6.22,-57.75,Casa do Ian😎
531,Orange Cove,US,75.20,36.62,-119.31,

In [72]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [60]:
#info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [61]:
# Store the DataFrame Row.
#hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]